### ISSUE TITLE
add #define NOGDI and #define NOMINMAX in juce_mongoose.h to avoid ambiguous calls to Rectangle and std::min/max

### ISSUE THREAD

**Issue by benkuper** [cpenny42/juce_mongoose#1]
Reference thread of the problem : https://forum.juce.com/t/rectangle-ambiguous-symbol/6891/5
I have other modules that are not explicitly using juce::Rectangle, using this module creates ambiguous call compile errors.
Just adding #define  NOGDI and #define NOMINMAX in juce_mongoose.h, line 26  resolves it :
```
#pragma once
#define JUCE_MONGOOSE_H_INCLUDED
#define NOGDI 
#define NOMINMAX
```

**Comment by cpenny42** [comment]
Thanks! Just pushed your fix.
